project:
  type: website
  output-dir: docs
  resources:
    - CNAME
  render: 
    - pages/home.qmd
    - pages/hrojects.qmd
    - pages/photography.qmd
    - pages/contact.qmd
  
website:
  title: ""
  search: false
  navbar:
    pinned: true

    left:
      - href: pages/home.qmd
        text: Daniel Allman
        
    right:
      - href: pages/projects.qmd
        text: Projects
      - href: pages/photography.qmd
        text: Photography
      - href: pages/contact.qmd
        text: Contact
        
      - icon: mortarboard
        href: https://scholar.google.com.au/citations?view_op=list_works&hl=en&user=EJzZvOYAAAAJ&gmla=AIfU4H76cl-gMSFa6zlgdAhH02pVZVMqxO4gnIpnafhIses84Bxx6BBCA4xEdmc-Gj7XbaAxlbUM8f3oSQK_nN3ZKM0cmALZ-ZTPsFHeshgHk34u_TtS
        target: _blank
      - icon: person-circle
        href: https://orcid.org/0009-0000-2249-2841
        target: _blank

  page-footer:
    right: "&copy; Copyright 2025, Daniel Allman"

format:
  html:
    theme: simplex

editor: source

